// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Type       string
	Name       string
	Login      string
	Password   string
	Data       []byte
	CardNumber string
	CardExp    string
	CardCvv    string
	Meta       string
	UpdatedAt  time.Time
}

type User struct {
	ID            uuid.UUID
	Login         string
	PasswordHash  string
	KekSalt       []byte
	DekCiphertext []byte
	CreatedAt     time.Time
}
