// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, user_id, type, name, login, password, data, card_number, card_exp, card_cvv, meta, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, type, name, login, password, data, card_number, card_exp, card_cvv, meta, updated_at
`

type CreateItemParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Type       string
	Name       string
	Login      string
	Password   string
	Data       []byte
	CardNumber string
	CardExp    string
	CardCvv    string
	Meta       string
	UpdatedAt  time.Time
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Login,
		arg.Password,
		arg.Data,
		arg.CardNumber,
		arg.CardExp,
		arg.CardCvv,
		arg.Meta,
		arg.UpdatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.Data,
		&i.CardNumber,
		&i.CardExp,
		&i.CardCvv,
		&i.Meta,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, login, password_hash, kek_salt, dek_ciphertext)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, login, password_hash, kek_salt, dek_ciphertext, created_at
`

type CreateUserParams struct {
	ID            uuid.UUID
	Login         string
	PasswordHash  string
	KekSalt       []byte
	DekCiphertext []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.KekSalt,
		arg.DekCiphertext,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.KekSalt,
		&i.DekCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items
WHERE id = $1 AND user_id = $2
`

type DeleteItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItem = `-- name: GetItem :one
SELECT id, user_id, type, name, login, password, data, card_number, card_exp, card_cvv, meta, updated_at
FROM items
WHERE id = $1 AND user_id = $2
`

type GetItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.UserID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.Data,
		&i.CardNumber,
		&i.CardExp,
		&i.CardCvv,
		&i.Meta,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash, kek_salt, dek_ciphertext, created_at
FROM users
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.KekSalt,
		&i.DekCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, password_hash, kek_salt, dek_ciphertext, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.KekSalt,
		&i.DekCiphertext,
		&i.CreatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, user_id, type, name, login, password, data, card_number, card_exp, card_cvv, meta, updated_at
FROM items
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListItems(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Login,
			&i.Password,
			&i.Data,
			&i.CardNumber,
			&i.CardExp,
			&i.CardCvv,
			&i.Meta,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, user_id, name, size, meta, s3_key, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, size, meta, s3_key, updated_at
`

type CreateFileParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Size      int64
	Meta      string
	S3Key     string
	UpdatedAt time.Time
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Size,
		arg.Meta,
		arg.S3Key,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.Meta,
		&i.S3Key,
		&i.UpdatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, user_id, name, size, meta, s3_key, updated_at
FROM files
WHERE id = $1 AND user_id = $2
`

type GetFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRow(ctx, getFile, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.Meta,
		&i.S3Key,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, user_id, name, size, meta, s3_key, updated_at
FROM files
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListFiles(ctx context.Context, userID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Size,
			&i.Meta,
			&i.S3Key,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFile = `-- name: DeleteFile :execrows
DELETE FROM files
WHERE id = $1 AND user_id = $2
`

type DeleteFileParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
