// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: gophkeeper/v1/gophkeeper.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemType describes the kind of secret stored in an Item.
type ItemType int32

const (
	ItemType_ITEM_TYPE_UNSPECIFIED ItemType = 0
	ItemType_LOGIN                 ItemType = 1
	ItemType_TEXT                  ItemType = 2
	ItemType_BINARY                ItemType = 3
	ItemType_CARD                  ItemType = 4
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNSPECIFIED",
		1: "LOGIN",
		2: "TEXT",
		3: "BINARY",
		4: "CARD",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNSPECIFIED": 0,
		"LOGIN":                 1,
		"TEXT":                  2,
		"BINARY":                3,
		"CARD":                  4,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_gophkeeper_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest carries credentials for a new user.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterResponse is returned on successful registration.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// LoginRequest carries credentials of an existing user.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse is returned on successful login.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// PingResponse confirms that the server is reachable and the token is valid.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Item is a single secret owned by a user.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ItemType               `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.ItemType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Login         string                 `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	CardNumber    string                 `protobuf:"bytes,7,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardExp       string                 `protobuf:"bytes,8,opt,name=card_exp,json=cardExp,proto3" json:"card_exp,omitempty"`
	CardCvv       string                 `protobuf:"bytes,9,opt,name=card_cvv,json=cardCvv,proto3" json:"card_cvv,omitempty"`
	Meta          string                 `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ITEM_TYPE_UNSPECIFIED
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Item) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Item) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Item) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *Item) GetCardExp() string {
	if x != nil {
		return x.CardExp
	}
	return ""
}

func (x *Item) GetCardCvv() string {
	if x != nil {
		return x.CardCvv
	}
	return ""
}

func (x *Item) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateItemRequest asks the server to store a new Item.
type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *CreateItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// CreateItemResponse returns the id of the created Item.
type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *CreateItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetItemRequest identifies the Item to fetch.
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetItemResponse contains the requested Item.
type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// ListItemsRequest asks for all items of the current user.
type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{10}
}

// ListItemsResponse contains all items of the current user.
type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// DeleteItemRequest identifies the Item to delete.
type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteItemResponse reports the result of deletion.
type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteItemResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1egophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xc3\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.gophkeeper.v1.ItemTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05login\x18\x04 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1f\n" +
	"\vcard_number\x18\a \x01(\tR\n" +
	"cardNumber\x12\x19\n" +
	"\bcard_exp\x18\b \x01(\tR\acardExp\x12\x19\n" +
	"\bcard_cvv\x18\t \x01(\tR\acardCvv\x12\x12\n" +
	"\x04meta\x18\n" +
	" \x01(\tR\x04meta\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"<\n" +
	"\x11CreateItemRequest\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"$\n" +
	"\x12CreateItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fGetItemResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.gophkeeper.v1.ItemR\x04item\"\x12\n" +
	"\x10ListItemsRequest\">\n" +
	"\x11ListItemsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.gophkeeper.v1.ItemR\x05items\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteItemResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*P\n" +
	"\bItemType\x12\x19\n" +
	"\x15ITEM_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LOGIN\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\n" +
	"\n" +
	"\x06BINARY\x10\x03\x12\b\n" +
	"\x04CARD\x10\x042\x9a\x04\n" +
	"\n" +
	"GophKeeper\x12K\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponse\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse\x12;\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1b.gophkeeper.v1.PingResponse\x12Q\n" +
	"\n" +
	"CreateItem\x12 .gophkeeper.v1.CreateItemRequest\x1a!.gophkeeper.v1.CreateItemResponse\x12H\n" +
	"\aGetItem\x12\x1d.gophkeeper.v1.GetItemRequest\x1a\x1e.gophkeeper.v1.GetItemResponse\x12N\n" +
	"\tListItems\x12\x1f.gophkeeper.v1.ListItemsRequest\x1a .gophkeeper.v1.ListItemsResponse\x12Q\n" +
	"\n" +
	"DeleteItem\x12 .gophkeeper.v1.DeleteItemRequest\x1a!.gophkeeper.v1.DeleteItemResponseBAZ?github.com/kmorozov/gophkeeper/proto/gophkeeper/v1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_v1_gophkeeper_proto_rawDescData
}

var file_gophkeeper_v1_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(ItemType)(0),                 // 0: gophkeeper.v1.ItemType
	(*RegisterRequest)(nil),       // 1: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: gophkeeper.v1.RegisterResponse
	(*LoginRequest)(nil),          // 3: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),         // 4: gophkeeper.v1.LoginResponse
	(*PingResponse)(nil),          // 5: gophkeeper.v1.PingResponse
	(*Item)(nil),                  // 6: gophkeeper.v1.Item
	(*CreateItemRequest)(nil),     // 7: gophkeeper.v1.CreateItemRequest
	(*CreateItemResponse)(nil),    // 8: gophkeeper.v1.CreateItemResponse
	(*GetItemRequest)(nil),        // 9: gophkeeper.v1.GetItemRequest
	(*GetItemResponse)(nil),       // 10: gophkeeper.v1.GetItemResponse
	(*ListItemsRequest)(nil),      // 11: gophkeeper.v1.ListItemsRequest
	(*ListItemsResponse)(nil),     // 12: gophkeeper.v1.ListItemsResponse
	(*DeleteItemRequest)(nil),     // 13: gophkeeper.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil),    // 14: gophkeeper.v1.DeleteItemResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 16: google.protobuf.Empty
}
var file_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.Item.type:type_name -> gophkeeper.v1.ItemType
	15, // 1: gophkeeper.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: gophkeeper.v1.CreateItemRequest.item:type_name -> gophkeeper.v1.Item
	6,  // 3: gophkeeper.v1.GetItemResponse.item:type_name -> gophkeeper.v1.Item
	6,  // 4: gophkeeper.v1.ListItemsResponse.items:type_name -> gophkeeper.v1.Item
	1,  // 5: gophkeeper.v1.GophKeeper.Register:input_type -> gophkeeper.v1.RegisterRequest
	3,  // 6: gophkeeper.v1.GophKeeper.Login:input_type -> gophkeeper.v1.LoginRequest
	16, // 7: gophkeeper.v1.GophKeeper.Ping:input_type -> google.protobuf.Empty
	7,  // 8: gophkeeper.v1.GophKeeper.CreateItem:input_type -> gophkeeper.v1.CreateItemRequest
	9,  // 9: gophkeeper.v1.GophKeeper.GetItem:input_type -> gophkeeper.v1.GetItemRequest
	11, // 10: gophkeeper.v1.GophKeeper.ListItems:input_type -> gophkeeper.v1.ListItemsRequest
	13, // 11: gophkeeper.v1.GophKeeper.DeleteItem:input_type -> gophkeeper.v1.DeleteItemRequest
	2,  // 12: gophkeeper.v1.GophKeeper.Register:output_type -> gophkeeper.v1.RegisterResponse
	4,  // 13: gophkeeper.v1.GophKeeper.Login:output_type -> gophkeeper.v1.LoginResponse
	5,  // 14: gophkeeper.v1.GophKeeper.Ping:output_type -> gophkeeper.v1.PingResponse
	8,  // 15: gophkeeper.v1.GophKeeper.CreateItem:output_type -> gophkeeper.v1.CreateItemResponse
	10, // 16: gophkeeper.v1.GophKeeper.GetItem:output_type -> gophkeeper.v1.GetItemResponse
	12, // 17: gophkeeper.v1.GophKeeper.ListItems:output_type -> gophkeeper.v1.ListItemsResponse
	14, // 18: gophkeeper.v1.GophKeeper.DeleteItem:output_type -> gophkeeper.v1.DeleteItemResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_gophkeeper_proto_init() }
func file_gophkeeper_v1_gophkeeper_proto_init() {
	if File_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_gophkeeper_proto = out.File
	file_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
